perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "it_IT.UTF-8",
	LC_ADDRESS = "it_IT.UTF-8",
	LC_MONETARY = "it_IT.UTF-8",
	LC_NUMERIC = "it_IT.UTF-8",
	LC_TELEPHONE = "it_IT.UTF-8",
	LC_IDENTIFICATION = "it_IT.UTF-8",
	LC_MEASUREMENT = "it_IT.UTF-8",
	LC_TIME = "it_IT.UTF-8",
	LC_NAME = "it_IT.UTF-8",
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
2018-04-18 02:26:26,482 - SensorNodeFactory.create_nodes_auto() - INFO - skipping unknown node type
2018-04-18 02:26:26,484 - SensorNodeFactory.create_nodes_auto() - INFO - cc2538-bsl.py  -p /dev/ttyUSB1 -a 0x00202000
Opening port /dev/ttyUSB1, baud 500000 address 0x202000
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:10:03:52:FA
2018-04-18 02:26:26,941 - SensorNodeFactory.create_nodes_auto() - INFO - b''
2018-04-18 02:26:26,942 - SensorNodeFactory.create_nodes_auto() - INFO - Found Zoul on /dev/ttyUSB1
2018-04-18 02:26:29,536 - CoAPWrapper.2.__init__() - INFO - sudo ../../agent_modules/contiki/communication_wrappers/bin/tunslip6 -C -B 115200 -s /dev/ttyUSB1 fd00:c:2::1/64
<wishful_module_gitar.lib_arm_cortex_m.Zoul object at 0x73742830>
2018-04-18 02:26:30,640 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 inet `hostname` mtu 1500 up
2018-04-18 02:26:30,667 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fd00:c:2::1/64
2018-04-18 02:26:30,690 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0 add fe80::c:2:0:1/64
2018-04-18 02:26:30,704 - Thread-1   - CoAPWrapper.2 - INFO - ifconfig tun0
2018-04-18 02:26:30,706 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-18 02:26:30,713 - Thread-1   - CoAPWrapper.2 - INFO - tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
2018-04-18 02:26:30,715 - Thread-1   - CoAPWrapper.2 - INFO - inet addr:127.0.0.1  P-t-P:127.0.0.1  Mask:255.255.255.255
2018-04-18 02:26:30,716 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fe80::c:2:0:1/64 Scope:Link
2018-04-18 02:26:30,717 - Thread-1   - CoAPWrapper.2 - INFO - inet6 addr: fd00:c:2::1/64 Scope:Global
2018-04-18 02:26:30,718 - Thread-1   - CoAPWrapper.2 - INFO - UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
2018-04-18 02:26:30,722 - Thread-1   - CoAPWrapper.2 - INFO - RX packets:0 errors:0 dropped:0 overruns:0 frame:0
2018-04-18 02:26:30,723 - Thread-1   - CoAPWrapper.2 - INFO - TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
2018-04-18 02:26:30,724 - Thread-1   - CoAPWrapper.2 - INFO - collisions:0 txqueuelen:500
2018-04-18 02:26:30,725 - Thread-1   - CoAPWrapper.2 - INFO - RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
2018-04-18 02:26:30,726 - Thread-1   - CoAPWrapper.2 - INFO - 
2018-04-18 02:26:31,296 - Thread-1   - CoAPWrapper.2 - INFO - Got configuration message of type C
2018-04-18 02:26:31,298 - Thread-1   - CoAPWrapper.2 - INFO - Setting prefix fd00:c:2::
2018-04-18 02:26:31,299 - Thread-1   - CoAPWrapper.2 - INFO - Removing wishful_control_address: fd00:c::2
2018-04-18 02:26:31,300 - Thread-1   - CoAPWrapper.2 - INFO - New wishful_control_address: fd00:c:2::2
2018-04-18 02:26:32,283 - Thread-1   - CoAPWrapper.2 - INFO - Control prefix set and apps started
<Task pending coro=<coap_event_server() running at /export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py:106>>
2018-04-18 02:26:43,250 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-18 02:26:45,251 - Thread-3   - pyre_discovery_module.main - INFO - Discovered Controller DL-tcp://10.1.1.1:8990, UL-tcp://10.1.1.1:8989
2018-04-18 02:27:18,248 - Thread-1   - CoAPWrapper.2 - INFO - PEEE 21
local monitor cp started - Name: ecoap_local_monitoring_program_cocoa_cc, Id: 1 - STARTED
2018-04-18 02:27:58,843 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-18 02:28:00,894 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-18 02:28:02,940 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-18 02:28:04,987 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-18 02:28:07,034 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-18 02:28:08,039 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-18 02:28:09,044 - local_control_program - Contiki Base Connector - INFO - Attr IEEE802154_measurement_macStats not found
2018-04-18 02:28:09,045 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-18 02:28:09,047 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-18 02:28:09,048 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-18 02:28:09,049 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-18 02:28:09,050 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-18 02:28:09,051 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-18 02:28:09,051 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-18 02:28:10,058 - local_control_program - Contiki Base Connector - INFO - Attr coap_rx_success not found
2018-04-18 02:28:10,059 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_failed not found
2018-04-18 02:28:10,060 - local_control_program - Contiki Base Connector - INFO - Attr ipv6_stats not found
2018-04-18 02:28:10,061 - local_control_program - Contiki Base Connector - INFO - Attr capacity not found
2018-04-18 02:28:10,062 - local_control_program - Contiki Base Connector - INFO - Attr burst_start_event not found
2018-04-18 02:28:10,063 - local_control_program - Contiki Base Connector - INFO - Attr app_stats not found
2018-04-18 02:28:10,064 - local_control_program - Contiki Base Connector - INFO - Attr rpl_preferred_parent not found
2018-04-18 02:28:10,065 - local_control_program - Contiki Base Connector - INFO - Attr coap_tx_success not found
2018-04-18 02:28:10,065 - local_control_program - Contiki Base Connector - INFO - Attr rpl_rank not found
2018-04-18 02:28:10,066 - local_control_program - Contiki Base Connector - INFO - Attr coap_rto not found
2018-04-18 02:28:10,067 - local_control_program - Contiki Base Connector - INFO - Attr burst_end_event not found
2018-04-18 02:28:30,451 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process startup initiated!
2018-04-18 02:28:30,452 - Thread-1   - CoAPWrapper.2 - INFO - UDP client process started!
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 203, in set_parameters
    resp_key_values[param.name] = ControlDataType(self.platform.endianness_fmt, self.platform.get_data_type_format_by_name('INT8')).read_bytes(response_message[line_ptr:])
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/lib_gitar.py", line 38, in read_bytes
    tpl = struct.unpack(tmp_fmt, buf)
struct.error: unpack requires a bytes object of length 1
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 203, in set_parameters
    resp_key_values[param.name] = ControlDataType(self.platform.endianness_fmt, self.platform.get_data_type_format_by_name('INT8')).read_bytes(response_message[line_ptr:])
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/lib_gitar.py", line 38, in read_bytes
    tpl = struct.unpack(tmp_fmt, buf)
struct.error: unpack requires a bytes object of length 1
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 274, in read_measurements
    resp_key_values[measurement.name] = measurement.datatype.read_bytes(response_message[line_ptr:])
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/lib_gitar.py", line 38, in read_bytes
    tpl = struct.unpack(tmp_fmt, buf)
struct.error: unpack requires a bytes object of length 16
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 56, in get_net_measurements_periodic_worker
    ret = node.read_measurements(measurement_list)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 274, in read_measurements
    resp_key_values[measurement.name] = measurement.datatype.read_bytes(response_message[line_ptr:])
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/lib_gitar.py", line 38, in read_bytes
    tpl = struct.unpack(tmp_fmt, buf)
struct.error: unpack requires a bytes object of length 40
2018-04-18 02:34:36,158 - Dummy-1365 - coap - INFO - Duplicate CON received, no response to send yet
2018-04-18 02:34:40,103 - Dummy-1365 - coap - INFO - Duplicate CON received, no response to send yet
2018-04-18 02:34:47,994 - Dummy-1365 - coap - INFO - Duplicate CON received, no response to send yet
2018-04-18 02:35:03,775 - Dummy-1365 - coap - INFO - Duplicate CON received, no response to send yet
2018-04-18 02:35:35,346 - Dummy-1365 - coap - INFO - Duplicate CON received, no response to send yet
2018-04-18 02:36:09,168 - Dummy-1365 - coap.requester - INFO - Request timed out
Traceback (most recent call last):
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_contikibase/net_connector_module.py", line 25, in set_net_parameter
    return node.set_parameters(param_list, param_key_values_dict)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/wishful_module_gitar/rpc_node.py", line 196, in set_parameters
    response_message = self.com_wrapper.send(request_message)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 86, in send
    send_loop.run_until_complete(self.coap_send(send_loop, payload))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/export/home/testbed-user/wishful_raspberry/dev/lib/python3.4/site-packages/communication_wrappers/coap_wrapper.py", line 73, in coap_send
    response = yield from context.request(request).response
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
aiocoap.error.RequestTimedOut
2018-04-18 02:38:59,582 - Thread-1   - CoAPWrapper.2 - INFO - Buffer full, Req id 2441
bash: line 1: 18946 Terminated              python agent.py --config ecoap_external_advanced/ecoap_agent.yaml
